[tox]
envlist = py39, py310, py311, py312, py313, lint
isolated_build = True
skip_missing_interpreters = True

[testenv]
package = wheel
usedevelop = false
changedir = {toxinidir}
deps =
    pytest>=8.0
    pytest-cov>=5.0
commands =
    pytest tests {posargs}

[testenv:lint]
basepython = python3.9
skip_install = true
changedir = {toxinidir}
deps =
    black>=24,<26
    ruff>=0.6.9,<0.16.0
commands =
    black --check .
    ruff check .
